-- Esquema tal como lo dejo Hibernate (ddl-auto=update) antes de la Fase 1.
-- En una base existente Flyway NO ejecuta este script (baseline-version=1); solo crea las tablas en bases vacias.
CREATE TABLE agencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    descripcion text,
    direccion varchar(255),
    email_contacto varchar(255),
    fecha_alta timestamp(6),
    logo varchar(255),
    nombre varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    telefono_contacto varchar(255),
    CONSTRAINT agencias_pkey PRIMARY KEY (id),
    CONSTRAINT ukav7uu38c6bbsvc80sy4bfsh6j UNIQUE (slug)
);

CREATE TABLE usuarios (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    fecha_registro timestamp(6),
    nombre varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    rol varchar(255) NOT NULL,
    telefono varchar(255),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email),
    CONSTRAINT usuarios_rol_check CHECK (rol in ('ADMIN', 'COMPRADOR'))
);

CREATE TABLE publicaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    anio integer NOT NULL,
    color varchar(255),
    combustible varchar(255),
    condicion varchar(255),
    descripcion text,
    estado varchar(255),
    fecha_publicacion timestamp(6),
    kilometraje integer,
    marca varchar(255) NOT NULL,
    modelo varchar(255) NOT NULL,
    moneda varchar(255),
    precio numeric(12,2) NOT NULL,
    transmision varchar(255),
    admin_id bigint NOT NULL,
    agencia_id bigint NOT NULL,
    CONSTRAINT publicaciones_pkey PRIMARY KEY (id),
    CONSTRAINT publicaciones_combustible_check CHECK (combustible in ('NAFTA', 'DIESEL', 'GNC', 'HIBRIDO', 'ELECTRICO')),
    CONSTRAINT publicaciones_condicion_check CHECK (condicion in ('EXCELENTE', 'MUY_BUENO', 'BUENO', 'REGULAR')),
    CONSTRAINT publicaciones_estado_check CHECK (estado in ('DISPONIBLE', 'RESERVADO', 'VENDIDO')),
    CONSTRAINT publicaciones_transmision_check CHECK (transmision in ('MANUAL', 'AUTOMATICA')),
    CONSTRAINT fk4we40j4h5dcqgb5qcdrwiuvmd FOREIGN KEY (admin_id) REFERENCES usuarios (id),
    CONSTRAINT fkhmv7xu8ff7aa0twbu24wsbscb FOREIGN KEY (agencia_id) REFERENCES agencias (id)
);

CREATE TABLE fotos_publicacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    orden integer,
    url varchar(255) NOT NULL,
    publicacion_id bigint NOT NULL,
    CONSTRAINT fotos_publicacion_pkey PRIMARY KEY (id),
    CONSTRAINT fkb859gbcnh6nbr62akqoquy20m FOREIGN KEY (publicacion_id) REFERENCES publicaciones (id)
);

CREATE TABLE consultas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email_comprador varchar(255) NOT NULL,
    fecha timestamp(6),
    mensaje text,
    nombre_comprador varchar(255) NOT NULL,
    telefono_comprador varchar(255),
    publicacion_id bigint NOT NULL,
    CONSTRAINT consultas_pkey PRIMARY KEY (id),
    CONSTRAINT fknycgcr2xmas00xlcodcig611m FOREIGN KEY (publicacion_id) REFERENCES publicaciones (id)
);

CREATE TABLE favoritos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha timestamp(6),
    publicacion_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT favoritos_pkey PRIMARY KEY (id),
    CONSTRAINT uklbdxm8xrecugqmhfov0g8pvul UNIQUE (usuario_id, publicacion_id),
    CONSTRAINT fkgisq99c5dapg7un36hhysttlo FOREIGN KEY (publicacion_id) REFERENCES publicaciones (id),
    CONSTRAINT fkq9wif2hcqfxj8t49wo613wm0h FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
