-- "Vender tu auto": solicitudes de venta de usuarios (entidad SolicitudVenta).
-- La base de produccion ya tiene esta tabla (la creo Hibernate con ddl-auto=update antes de Flyway), por eso es
-- IF NOT EXISTS: en produccion no hace nada y en una base nueva (desarrollo, tests) la crea con el mismo esquema.

CREATE TABLE IF NOT EXISTS solicitudes_venta (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    anio integer NOT NULL,
    ciudad varchar(255),
    cotizacion_max numeric(38,2),
    cotizacion_min numeric(38,2),
    descripcion text,
    estado varchar(255) NOT NULL,
    fecha timestamp(6),
    kilometraje integer,
    marca varchar(255) NOT NULL,
    modelo varchar(255) NOT NULL,
    nombre_vendedor varchar(255) NOT NULL,
    telefono_vendedor varchar(255) NOT NULL,
    CONSTRAINT solicitudes_venta_pkey PRIMARY KEY (id),
    CONSTRAINT solicitudes_venta_estado_check CHECK (estado in ('PENDIENTE', 'CONTACTADO', 'DESCARTADO', 'CONCRETADO'))
);
