-- Fase 3: identidad completa y cuentas verificadas (D-01, D-04, D-06, D-09, D-10).
-- Todo es aditivo: la version anterior del back sigue funcionando contra esta base (es la vuelta atras de un deploy).
-- No se edita V1 a V4; no hay UPDATE de datos de usuarios salvo el mail confirmado de los ADMIN.

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS apellido varchar(255);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS dni varchar(8);
-- DEFAULT false: los mails de las cuentas existentes NO se dan por confirmados (D-10).
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email_confirmado boolean NOT NULL DEFAULT false;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS google_sub varchar(255);
-- Se actualiza al restablecer/cambiar la contrasena o al unir una cuenta con Google: los JWT emitidos antes dejan de valer.
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password_cambiada_en timestamp(6);
-- Una cuenta solo-Google no tiene contrasena.
ALTER TABLE usuarios ALTER COLUMN password_hash DROP NOT NULL;

-- En Postgres un UNIQUE permite muchos NULL: las cuentas viejas (sin DNI) conviven entre si (D-09). La obligatoriedad
-- de apellido y DNI vive en la regla de cuenta verificada, no en la base. Una cuenta por DNI (D-04).
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_dni UNIQUE (dni);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_google_sub UNIQUE (google_sub);
-- Formato del DNI (D-05): 7 u 8 digitos sin cero inicial, guardado sin puntos.
ALTER TABLE usuarios ADD CONSTRAINT usuarios_dni_formato CHECK (dni IS NULL OR dni ~ '^[1-9][0-9]{6,7}$');

-- El mail se compara sin distinguir mayusculas (Google devuelve minusculas; el login actual es sensible a mayusculas).
-- Sin UPDATE de mails a proposito: volver a la version anterior del back no deja sin acceso a nadie con mayusculas.
-- Si ya hubiera dos mails que difieren solo en mayusculas, esta sentencia falla y la migracion no deja nada a medias.
CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_email_lower ON usuarios (lower(email));

-- Los admins no compran ni cotizan: su mail se da por confirmado para que el gate nunca los moleste.
UPDATE usuarios SET email_confirmado = true WHERE rol = 'ADMIN';

-- Tokens de un solo uso para confirmar el mail y restablecer la contrasena. Se guarda el hash, nunca el token.
-- tipo sin CHECK: sumar un tipo de token no exige otra migracion.
CREATE TABLE tokens_cuenta (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint NOT NULL,
    tipo varchar(30) NOT NULL,
    token_hash varchar(64) NOT NULL,
    creado_en timestamp(6) NOT NULL,
    expira_en timestamp(6) NOT NULL,
    usado_en timestamp(6),
    CONSTRAINT tokens_cuenta_pkey PRIMARY KEY (id),
    CONSTRAINT uk_tokens_cuenta_hash UNIQUE (token_hash),
    CONSTRAINT fk_tokens_cuenta_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tokens_cuenta_usuario_tipo ON tokens_cuenta (usuario_id, tipo);
