-- Fase 4: conversaciones y mensajes con la agencia (D-01, D-02, D-03, D-13).
-- Todo es aditivo: solo se crean tablas e indices nuevos. No se edita V1 a V5 y no se toca ninguna fila existente;
-- la tabla consultas sigue como esta (la copia de sus datos y su retiro llegan despues, D-01), asi que la version
-- anterior del back sigue funcionando contra esta base (es la vuelta atras de un deploy).
-- Las fechas son timestamp(6) y se guardan en UTC (D-13): las fija el servicio con el reloj, no la base.

CREATE TABLE conversaciones (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo               varchar(20)  NOT NULL,
    estado             varchar(20)  NOT NULL,
    usuario_id         bigint       NOT NULL,
    -- Nulable: una conversacion de cotizacion (Fase 5) no tiene auto. Se borra junto con el auto (D-16).
    publicacion_id     bigint,
    creada_en          timestamp(6) NOT NULL,
    ultimo_mensaje_en  timestamp(6) NOT NULL,
    cerrada_en         timestamp(6),
    CONSTRAINT conversaciones_tipo_check CHECK (tipo IN ('COMPRA', 'COTIZACION')),
    CONSTRAINT conversaciones_estado_check CHECK (estado IN ('ABIERTA', 'CERRADA')),
    -- D-02: una conversacion de compra siempre tiene auto.
    CONSTRAINT conversaciones_compra_publicacion_check CHECK (tipo <> 'COMPRA' OR publicacion_id IS NOT NULL),
    CONSTRAINT fk_conversaciones_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_conversaciones_publicacion FOREIGN KEY (publicacion_id) REFERENCES publicaciones (id) ON DELETE CASCADE
);

CREATE TABLE mensajes (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversacion_id  bigint       NOT NULL,
    -- La cuenta que lo escribio. Del lado de la agencia es el admin; el usuario igual ve "Dante Automotores" (D-05).
    autor_id         bigint       NOT NULL,
    autor_tipo       varchar(20)  NOT NULL,
    texto            text         NOT NULL,
    creado_en        timestamp(6) NOT NULL,
    leido_en         timestamp(6),
    CONSTRAINT mensajes_autor_tipo_check CHECK (autor_tipo IN ('USUARIO', 'AGENCIA')),
    -- D-14: texto plano de 1 a 2000 caracteres.
    CONSTRAINT mensajes_texto_largo_check CHECK (char_length(texto) BETWEEN 1 AND 2000),
    CONSTRAINT fk_mensajes_conversacion FOREIGN KEY (conversacion_id) REFERENCES conversaciones (id) ON DELETE CASCADE,
    CONSTRAINT fk_mensajes_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

-- D-03: una sola conversacion ABIERTA de compra por usuario y auto; la base lo garantiza aunque falle la capa de arriba.
CREATE UNIQUE INDEX uk_conversaciones_compra_abierta ON conversaciones (usuario_id, publicacion_id)
    WHERE tipo = 'COMPRA' AND estado = 'ABIERTA';

CREATE INDEX idx_conversaciones_usuario ON conversaciones (usuario_id, ultimo_mensaje_en DESC);
CREATE INDEX idx_conversaciones_bandeja ON conversaciones (estado, ultimo_mensaje_en DESC);
CREATE INDEX idx_conversaciones_publicacion ON conversaciones (publicacion_id);
CREATE INDEX idx_mensajes_conversacion ON mensajes (conversacion_id, id);
CREATE INDEX idx_mensajes_no_leidos ON mensajes (autor_tipo, conversacion_id) WHERE leido_en IS NULL;
